### ISSUE TITLE
Calculation of Diffuse response using multi-processor tool

### ISSUE THREAD

**Issue by vaidehiratna** [fermiPy/gtapps_mp#6]
Dear Sir,

Since the release of Pass 8 data, gtltcube, and gtexpmap (using gtapps_mp) are working flawlessly, however, running gtdiffrsp throws following error

Caught St16invalid_argument at the top level: Invalid response function choice:
Traceback (most recent call last):
  File "gtdiffrsp_mp.py", line 144, in <module>
    if __name__ == '__main__': cli()
  File "gtdiffrsp_mp.py", line 142, in cli
    gtdiffrsp_mp(args.jobs, args.scfile, args.evfile, args.outfile, args.savetmp, args.srcmdl, args.irf)
  File "gtdiffrsp_mp.py", line 116, in gtdiffrsp_mp
    tempfilenames = pool.map(diffrsp,times.transpose())
  File "/home/Oracle/Softwares/ScienceTools-v10r0p5-fssc-20150518-x86_64-unknown-linux-gnu-libc2.18/x86_64-unknown-linux-gnu-libc2.18/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/Oracle/Softwares/ScienceTools-v10r0p5-fssc-20150518-x86_64-unknown-linux-gnu-libc2.18/x86_64-unknown-linux-gnu-libc2.18/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
RuntimeError: gtdiffrsp execution failed

My input is as follows
python gtdiffrsp_mp.py 3 _3FGLJ0849.9+5108_filtered_gti.fits _3FGLJ0849.9+5108_SC.fits _3FGLJ0849.9+5108_model.xml CALDB Diffrsp.fits

I found that in the earlier version of the ScienceTools, running gtdiffrsp command produced an output file, which is not the case of the current version (though I also tried with some output "Diffrsp.fits"). This issue is now more serious because running gtdiffrsp is compulsory in unbinned likelihood analysis.

In this regard, I request you to kindly update the "gtapps_mp" package for the use of latest ScienceTools software.

Thank you very much.

-- Vaidehi

**Comment by kialio** [comment]
Hello,

If you explicitly state the IRFs you would like to use, this will work.  I'll add in support for CALDB.

Jeremy

**Comment by kialio** [comment]
gtdiffrsp_mp can take CALDB as an option now.
